# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

first_n <- function(m, v, k) {
    .Call('_tsfknn_first_n', PACKAGE = 'tsfknn', m, v, k)
}

build_examples2 <- function(timeS, lags, nt) {
    .Call('_tsfknn_build_examples2', PACKAGE = 'tsfknn', timeS, lags, nt)
}

